# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DbUTF2QuBuAUptTDLuABWE0DjRDX4e9l
"""



num=int(input("enter the number"))
if (num%2==0):
       print("its even number")
else:
   print("its odd number")