# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Rwi3GWPUBDD7OHYnOo5AGIfdz2SAm_b
"""



num1=int(input("enter 1st number"))
num2=int(input("enter 2nd number"))
num3=int(input("enter 3rd number"))
result=(num1+num2)*num3
if(cal>100):
    print("result is greater than 100")
else:
    print("result is less than 100")