# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IAiWY9g655sBk0H86Z0fO8UBA5yt3Lft
"""

age=int(input("enter your age"))
if age>=18:
    print(" eligible to vote")
else:
       print("you are not eligible")