# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Icow3mygZ4PtPilUnlV3oxb-tIeFUDKb
"""



name=input("enter your name")
age=(input("enter your age"))
gender=input("enter your gender(male/female)" )
print("the name of the peson is  "+name +" of " +age+" and he is "+gender )